name: vision-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - pip:
      - fiftyone
      - anylabeling
      - imgviz<2
      - ultralytics
      - opencv-python
      - pillow
      - PyYAML
